### ISSUE TITLE
Support for principal tags/transitive tag keys in WebIdentityToken patch

### ISSUE THREAD

**Issue by nkoshcheev** [aws/amazon-eks-pod-identity-webhook#103]
**What would you like to be added**:
Support for setting a custom (ideally using an annotation for ServiceAccount) PrincipalTag for STS session (through patching of the WIT file: https://docs.aws.amazon.com/IAM/latest/UserGuide/id_session-tags.html, please see Passing session tags using AssumeRoleWithWebIdentity section). Transitive tag keys also might be valuable. 
**Why is this needed**:
That would eliminate necessity to maintain a lot of similar\identical IAM Roles, for example attribute-based S3 access for application-specific S3 keys might be implemented through this: EKS sets an app-specific PrincipalTag which is then used as a variable in IAM policy (e.g. with a default variable substitution within resource/key definition in a policy).

**Comment by micahhausler** [comment]
I would love this too! In order to support this, Kubernetes would need to support custom claims in JWT tokens it issues.  I'll close this out as it is a Kubernetes feature, not one for this webhook

kubernetes/kubernetes#61795
kubernetes/kubernetes#91610

**Comment by uCatu** [comment]
@micahhausler Just to clarify
Kubernetes is supporting only `kubernetes.io` claim, e.g:
```
"kubernetes.io": {
    "namespace": "ucatu-372c457ed6e742e29c1f0ca5751747e1",
    "pod": {
      "name": "cnj-372c457ed6e742e29c1f0ca5751747e1-975b5cd9d-27twb",
      "uid": "64f5c4d0-2c0e-4099-a2cc-e5cbdd4ec153"
    },
    "serviceaccount": {
      "name": "cnj-372c457ed6e742e29c1f0ca5751747e1",
      "uid": "5dd8b20a-8d08-4f58-8ffd-83326dfd1218"
    }
```
And to support session-tags they need to be under `https://aws.amazon.com/tags` claim, e.g ([from](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_session-tags.html#id_session-tags_adding-assume-role-idp) :
```
    "https://aws.amazon.com/tags": {
        "principal_tags": {
            "Project": ["Automation"],
            "CostCenter": ["987654"],
            "Department": ["Engineering"]
        },
        "transitive_tag_keys": [
            "Project",
            "CostCenter"
        ]
    }
```
Thus a possible workaround is to create another AWS role only for the purpose of `--tags` and replace the path on pod?
Thanks!

**Comment by micahhausler** [comment]
No, adding custom JWT claims is unsupported in Kubernetes. If you are using EKS and want to use session tags, that is supported with [EKS's Pod Identity](https://docs.aws.amazon.com/eks/latest/userguide/pod-id-abac.html).

**Comment by Shaked** [comment]
Thank you. 

The problem with EKS's Pod Identity is that it seems like I must associate the k8s ServiceAccount with the role before generating it.

Instead, what I'd like to achieve, is away to create a dynamic policy. Meaning that I will use `StringLike` and `"s3:prefix": "${aws:PrincipalTag/kubernetes-service-account}"` (or something similar). The k8s ServiceAccount is dynamically generated via automation. 

Any idea how I could achieve this?

**Comment by micahhausler** [comment]
> The problem with EKS's Pod Identity is that it seems like I must associate the k8s ServiceAccount with the role before generating it.

You can create the Pod Identity config without the SA existing yet, but you do need to have a consistent name ([see the note on point `e:` in the docs](https://docs.aws.amazon.com/eks/latest/userguide/pod-id-association.html#_create_a_pod_identity_association_cli)).
>> You can specify a namespace and service account by name that doesn’t exist in the cluster. You must create the namespace, service account, and the workload that uses the service account for the EKS Pod Identity association to function.

We don't support glob matching on Service Account names primarily because we want assignment of IAM roles to be as consistent and unsurprising as possible.

**Comment by Shaked** [comment]
@micahhausler maybe if I could associate the SA without stating the namespace, that would have partially solved the issue. But if I need to associate each SA and NS, it means that I have to provision them in advance, which is hard when there's a lot of them. 

> We don't support glob matching on Service Account names primarily because we want assignment of IAM roles to be as consistent and unsurprising as possible.

In the way that it works now, if I use EKS, it means that I have to basically create a role per SA and NS, since I need its policy to differ for each SA and NS. Is there a way to overcome this natively without coding my own solution? I have seen this question coming up a lot in issues/community forums so I'd assume that others would be happy to have this as well.

Thank you!
