### ISSUE TITLE
Single OIDC provider for multiple EKS clusters

### ISSUE THREAD

**Issue by santiagopoli** [aws/amazon-eks-pod-identity-webhook#23]
In my company, we create multiple Kubernetes clusters with EKS (for redundancy reasons). Those clusters have the exact same configuration (the same manifests/YAMLs which are hosted in a Git repository) . We are currently in the process of eliminating the need to use AWS Access Keys and replace them with AWS Roles.

The problem is that by following the tutorial provided in this repo, it seems that every cluster needs to have different OIDC providers, so we won't be able to use the exact same roles in our service accounts.

Is there a way to use a single OIDC provider for all of our clusters? I've followed the `Self-Hosted configuration` documentation, but it relies on changing the API Server flags, which is something that can't be done on EKS.

Another solution that came to mind is using wildcards in the Role's principals, but it's not secure (because with this approach, testing clusters created in the same account as a production cluster can assume roles for production services)

Something like

```
"Principal": {
  "Federated": "arn:aws:iam::1234:oidc-provider/oidc.us-west-2.eks.amazonaws.com/*"
},
```
I accept other suggestions though

Thanks!

**Comment by santiagopoli** [comment]
Maybe using a wildcard in the principal does the trick. I'll test it tomorrow

Something like

```
"Principal": {
  "Federated": "arn:aws:iam::111122223333:oidc-provider/oidc.us-west-2.eks.amazonaws.com/*"
},
```

**Comment by mutiger86** [comment]
@santiagopoli That syntax actually works.  Unfortunately, if you want to use the condition to scope down a specific service account, it no longer works because the subject claim name is different each for each cluster.

**Comment by micahhausler** [comment]
Thanks for opening this issue. A shared OIDC provider is not something we intend to support, because if this were the case, the signing keys for service account tokens would be the same on both clusters, resulting in a token from one cluster being usable with the API server on a separate cluster. This breaks cluster isolation in confusing and unintended ways.

You can reuse IAM roles for multiple EKS clusters though. The `Statement` field of the IAM role's trust policy is an array, so you'll need to add each cluster as a trusted provider. 

```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Federated": "arn:aws:iam::${AWS::AccountId}:oidc-provider/oidc.eks.${AWS::Region}.amazonaws.com/id/${Cluster_1}"
      },
      "Action": "sts:AssumeRoleWithWebIdentity",
      "Condition": {
        "StringEquals": {
          "oidc.eks.${AWS::Region}.amazonaws.com/id/${Cluster_1}:sub": "system:serviceaccount:${Namespace}:default"
        }
      }
    },
    {
      "Effect": "Allow",
      "Principal": {
        "Federated": "arn:aws:iam::${AWS::AccountId}:oidc-provider/oidc.eks.${AWS::Region}.amazonaws.com/id/${Cluster_2}"
      },
      "Action": "sts:AssumeRoleWithWebIdentity",
      "Condition": {
        "StringEquals": {
          "oidc.eks.${AWS::Region}.amazonaws.com/id/${Cluster_2}:sub": "system:serviceaccount:${Namespace}:default"
        }
      }
    }
  ]
}
```

Does that suit your use case?

**Comment by micahhausler** [comment]
Closing with no reply

**Comment by omerlh** [comment]
We have a similar situation, and now we’re trying to write tooling that can help with this issue. This is problematic in the following flows:
* when creating a service that need IAM permission: the developer need to know what are all the clusters, and add them to the role.
* when deploying a new cluster, the operator need to update all the roles with the new cluster oidc provider

Right now I built a small operator that read the requested policy from an annotation on the service. The operator creates a role, set up the oidc policy for the cluster it’s running on and attach the requested policy. Then, it set the annotation with the role name.

Maybe supported feature like that can be merged into this webhook? This will solve our issue

**Comment by micahhausler** [comment]
@omerlh This webhook doesn't interact with IAM at all, it is just a connivence layer for mutating pods. I do see the problem but I think its outside the scope of this webhook.

> The operator creates a role, set up the oidc policy for the cluster it’s running on and attach the requested policy.

While this technically works, manipulating role policies in-cluster is not something we want to encourage customers to do. `iam:CreateRole` and `iam:UpdateAssumeRolePolicy ` are _very_ privileged APIs, as the operator can create a role with any policy and can control who can assume any role (minus a possible [permission boundary](https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_boundaries.html)).  If your operator's policy was:

```json
{
  "Version":"2012-10-17",
  "Id": "DO-NOT-DO-THIS",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "iam:UpdateAssumeRolePolicy"
      ],
      "Resource": "*"
    }
  ]
}
```

and without a permission boundary, the operator could modify who can assume _any_ role in the account, including an Admin role.

**Comment by omerlh** [comment]
I agree, but there has to be some tool with those permissions. I don’t want devs to do those things manually, so it’s either operator or a CI process (terraform/cdk).

To make it more secure, I plan to enforce tags on the policy - specifying which service account can use this policy.

I hear your concern, but I do think providing costumers some guidance regarding how to use this in multi-cluster/multi accounts scenarios can be relevant.

While it’s out of scope of the webhook, maybe it can be another component? I’ll be happy to contribute the code.

**Comment by micahhausler** [comment]
I totally get it, this is not the kind of permission you want to give to arbitrary devs either. Its pretty impractical for EKS to pick just one recommended solution here because our customers use _so_ many different orchestration solutions on top. [eksctl can perform the kind of setup](https://eksctl.io/usage/iamserviceaccounts/) you're doing, but you're right that you'd need some engine (GitOps/Terraform/something else?) to actually do the execution.

That being said, I'm all for a separate tool that could do the orchestration. In building a separate tool, it'd be important to be sure it can be run as an out of cluster application. The scary thing about in-cluster is that with the above example setup, you're one public K8s 0-day or one misconfigured RBAC rule away from AWS account takeover, not just cluster takeover.

**Comment by omerlh** [comment]
I found a pretty neat solution - I moved role creation logic into a lambda, and the mutation webhook has only the permission to invoke it. The lambda validates the tags on the policies, so you can assume only very specific policies. If we can add another layer of validation to this webhook (what roles an SA can assume), it will be even better

**Comment by keerthi0489** [comment]
Hi, I know that this issue is closed but the issue is of interest to us. There is a hard limit of 100 OIDC providers for AWS account. This means we will not be able to provision more than 100 eks clusters in our account, I am not sure how we can overcome this. Any thoughts?

**Comment by micahhausler** [comment]
@keerthi0489 IAM will approve a limit increase for more than 100 providers in an account

**Comment by keerthi0489** [comment]
@micahhausler - Thanks for the response, I have already opened a limit increase case with them, since this is a hard limit , I am not so sure they will. Have you been able to get that increased on your account?

**Comment by micahhausler** [comment]
I've previously confirmed with the IAM team that > 100 will be approved.

**Comment by alexef** [comment]
Hi @micahhausler !
> You can reuse IAM roles for multiple EKS clusters though. The Statement field of the IAM role's trust policy is an array, so you'll need to add each cluster as a trusted provider.

The problem we are facing setting up multiple identical clusters in the same AWS account is that the IAM role trust policy is also limited in size, so once we have 11 clusters we cannot trust more oidc providers using this strategy.

Do you have a suggestion for us? Our use case is dynamic test clusters, again with identical manifests/iam roles etc.

**Comment by artem-nefedov** [comment]
Hi. I know it was said that shared OIDC providers won't be supported, but I'm wondering if something changed since then and there's possibility for reconsideration. It would in fact help us very much in the following usecase:

We want to use blue/green strategy for EKS cluster upgrades. Meaning that, instead of upgrading live cluster in-place, we instead bring up a second cluster near it, switch traffic to it, then delete the old cluster if everything is ok. The new cluster runs all exact same apps with the exact same versions like the old cluster, and everything is automatically deployed by a GitOps controller reading from the same source as previous cluster.

In this case, we want to be able to bring up the new cluster and immediately allow GitOps controller to install all apps without making any changes to application-specific infra in AWS, because app infra is shared between both clusters, and it should be decoupled from cluster deployment. So far, this works well for everything except IAM roles for service accounts, because the trust policies in roles require knowledge of OIDC url, which only becomes known after cluster is created.

Shared OIDC provider for both clusters would be a perfect solution. We could create IAM roles for both clusters ahead of time, and treat it just as any other app-related infra. The fact that token for one cluster can be used on another one isn't a concern in this particular case.

**Comment by phillebaba** [comment]
I totally agree with @artem-nefedov  statement. We are currently using the same solution but when we want to upgrade a cluster all teams need to add the new OIDC url to their Terraform vars and apply the changes. This is really a sub-optimal solution with large amounts of risks. Having the ability to seamlessly replacing a cluster without changing IAM roles would be very nice.

**Comment by ghostsquad** [comment]
@phillebaba you can disassociate an EKS cluster from the OIDC provider it "comes with" and reassociate it with a shared OIDC provider. But this requires the masters to be rebooted, which can take some time (10-40 minutes).

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_identity_provider_config

**Comment by timblaktu** [comment]
@artem-nefedov, @phillebaba as it seems the "1 cluster per OIDC provider" rule stands, I'm curious if you came upon any more elegant solution to managing identical staging/prod EKS clusters using OIDC. My assumption is that you have to create separate OIDC provider environments to match each EKS environment, then switch using `eks_identity_provider_config` terraform resource when blue switches to green? (hoping that the blue OIDC env was truly identical to the green OIDC env).

We are using Okta as OIDC provider for EKS in order to elegantly provide RBAC solution to large pool of users (already using Okta for AuthN). I was hoping I wouldn't have to manage separate Okta instances for every EKS instance, since we are using CI/CD for deploying the EKS clusters themselves and commonly create-test-destroy an ephemeral cluster per PR, not to mention dev, qa, staging, and prod.

**Comment by phillebaba** [comment]
So I have started looking at the solution you mention with `eks_identity_provider_config`, but it may take a while for me to get around figuring something out. My hope is to create a new shared oidc provider in AWS and add it to all EKS clusters. I have no idea if this will actually work with IRSA, but it is worth a try to see if it is possible. I have not found any blog post that claim that this works so if you find any please share!

**Comment by timblaktu** [comment]
@artem-nefedov, @phillebaba, @ghostsquad, It's not clear to me what precisely "doesn't work" about assigning the same OIDC provider to multiple EKS clusters. Does it fail at the EKS configuration step (i.e. does EKS configuration page issue an error recognizing this has happened?), or is the main problem the security issue mentioned by @micahhausler of having multiple clusters receiving the same signing keys for service account tokens, thereby allowing a token from one cluster being usable with the API server on another. 

If the main issue is the latter, would anyone agree that it's reasonable to accept this risk within testing environments only accessible on private networks?

To ensure each of our many test clusters has its own Okta OIDC provider instance, we are faced with having to either:

1. Pre-create a pool of Okta instances and designing a resource management system to dole them out to ephemeral EKS clusters in a mutually exclusive way. OR
2. Use the Okta API to automatically create a new Okta instance on the fly to associate with each new EKS cluster. (I'm not even sure this is possible after a quick look at [the docs](https://developer.okta.com/docs/reference/))

**Comment by maradwan** [comment]
Why you didn't use lambda to create OIDC? It is just invoked when a new cluster is created.

**Comment by ethompsy** [comment]
There must be a way around this? We are running multi-tenant EKS clusters and are moving toward being multi-region with Istio service. Not only does this mean we need to coordinate OIDC providers and shared trust policies between our regions and tiers (Stable and Beta), but all of our tenants will need to update their cross-account trust policies EVERY time we want to rebuild a cluster or add a cluster. This will cause inter-team dependencies that are not scalable.

Can't there be an option for sharing OIDC between clusters with a disclaimer or something?

**Comment by liubog2008** [comment]
> Jan 2022 edit: The IAM team is not approving limit increases, this is a hard limit for them.

So how to resolve this problem, I think this issue should be reopened ? @micahhausler

**Comment by balusarakesh** [comment]
@micahhausler 
can you open this issue please OR provider alternatives?

we have a use-case to create a bunch of temporary test clusters for engineers to replicate our existing environment which lasts only a few hours, it is not feasible for us to update all IAM roles and the limitations on the trust relationship policy is very small that we can barely allow only 2-3 clusters.

**Comment by maradwan** [comment]
You can use Lambda to create the OIDC https://dev.to/aws-builders/using-lambda-to-automate-oidc-and-iam-role-for-service-account-in-eks-c0e

**Comment by balusarakesh** [comment]
> You can use Lambda to create the OIDC https://dev.to/aws-builders/using-lambda-to-automate-oidc-and-iam-role-for-service-account-in-eks-c0e

@maradwan 
this is also not a reasonable solution for us as our test apps running on these temporary clusters share the same AWS resources and for every new cluster we create we have to update the AWS resources like SQS queue or an SNS topic to allow the new IAM role

**Comment by balusarakesh** [comment]
For someone still looking for a solution to this the workaround we used is to create kubernetes clusters using third-party tools like [kind](https://github.com/kubernetes-sigs/kind) and setup a custom OIDC provider by following the docs [here](https://github.com/aws/amazon-eks-pod-identity-webhook/blob/master/SELF_HOSTED_SETUP.md). You can use the same OIDC provider for multiple clusters and it works fine.

**Comment by valorl** [comment]
Same use-case as @artem-nefedov here. Blue/green style cluster-level failovers and using FluxCD to make sure new clusters automatically run all our applications. Therefore, we very much like to avoid any kind of coupling of an application to a specific cluster. It should work on any cluster running in an environment/account. Having to update N roles every time we add/delete a cluster is a lot of unnecessary overhead. 

A shared, pre-provisioned OIDC provider would work of course solve this. Seems like https://github.com/aws/containers-roadmap/issues/1579 may be a better home for this.

As OP also touched on, a more flexible policy definition, where an application's IRSA role can simply work for all clusters in the account, would also work for us, e.g.:
```json
{
  "Effect": "Allow",
  "Principal": {
    "Federated": "arn:aws:iam::111111111111:oidc-provider/oidc.eks.eu-central-1.amazonaws.com/id/*"
  },
  "Action": "sts:AssumeRoleWithWebIdentity",
  "Condition": {
    "StringEquals": {
      "oidc.eks.eu-central-1.amazonaws.com/id/*:sub": "system:serviceaccount:namespace:app"
    }
  }
}
```

**Comment by rohitagarwal003** [comment]
A lot of the concerns from here seem to be addressed in https://aws.amazon.com/blogs/aws/amazon-eks-pod-identity-simplifies-iam-permissions-for-applications-on-amazon-eks-clusters/

**Comment by Danielkiss9** [comment]
Hi,
Is there a solution for this?
iam pods access won't work as it requires manually attaching the service account for to role every time as im aware of.

**Comment by atamgp** [comment]
@micahhausler van we reopen this?

**Comment by dothinh316** [comment]
+1 please repen
